# Generated by Django 4.1.2 on 2022-10-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_pix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pix',
            new_name='profile_picture',
        ),
    ]
