# Generated by Django 4.1.2 on 2022-10-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_product_discount_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_one', models.ImageField(upload_to='banners')),
                ('banner_two', models.ImageField(upload_to='banners')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
