# Generated by Django 4.1.2 on 2022-10-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_alter_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
