# Generated by Django 4.1.2 on 2022-10-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_alter_product_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
    ]
