# Generated by Django 4.1.2 on 2022-10-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_remove_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
