# Generated by Django 4.1.2 on 2022-10-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_remove_product_slug_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(max_length=100),
        ),
    ]
