# Generated by Django 4.1.2 on 2022-10-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_cart_order_cartproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='total',
        ),
    ]
