# Generated by Django 4.1.2 on 2022-10-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0020_alter_cart_profile_alter_cartproduct_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Paystack', 'Paystack'), ('Cash On Delivery', 'Cash On Delivery'), ('Bank Transfer', 'Bank Transfer')], default='Cash On Delivery', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
